// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';
import {downloader} from '../models';
import {metadata} from '../models';

export function AddFiles(arg1:Array<string>):Promise<library.BatchResult>;

export function ChooseDownloadFolder():Promise<string>;

export function DownloadMedia(arg1:string,arg2:string,arg3:string,arg4:string):Promise<downloader.DownloadResult>;

export function DownloaderStatus():Promise<downloader.Status>;

export function GetAudioState():Promise<Record<string, number>>;

export function LoadAudio(arg1:string):Promise<void>;

export function LoadLibrary():Promise<Array<string>>;

export function LoadLibraryWithMetadata():Promise<library.BatchResult>;

export function LoadMetadata(arg1:string):Promise<metadata.TrackMetadata>;

export function PauseAudio():Promise<void>;

export function PlayAudio():Promise<void>;

export function ResetAppData():Promise<void>;

export function SaveLibrary(arg1:Array<string>):Promise<void>;

export function SaveMetadata(arg1:metadata.TrackMetadata):Promise<void>;

export function SaveMetadataAndRefresh(arg1:metadata.TrackMetadata):Promise<metadata.TrackMetadata>;

export function SeekAudio(arg1:number):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SetVolume(arg1:number):Promise<void>;

export function StartDownloader():Promise<void>;

export function StopDownloader():Promise<void>;

export function ToggleAudio():Promise<boolean>;
