// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';
import {main} from '../models';
import {downloader} from '../models';
import {media} from '../models';
import {metadata} from '../models';
import {soundcloud} from '../models';

export function AddFiles(arg1:Array<string>):Promise<library.BatchResult>;

export function BulkUpdateMetadata(arg1:Array<string>,arg2:main.BulkMetadataPatch):Promise<main.BulkUpdateResult>;

export function ChooseDownloadFolder():Promise<string>;

export function DeleteTrimBackup(arg1:string):Promise<void>;

export function DownloadMedia(arg1:string,arg2:string,arg3:string,arg4:string):Promise<downloader.DownloadResult>;

export function DownloaderStatus():Promise<downloader.Status>;

export function ExtractAudioFromVideo(arg1:string,arg2:string,arg3:string):Promise<main.ExtractAudioResult>;

export function GetAudioState():Promise<Record<string, number>>;

export function GetDownloaderAutoStart():Promise<boolean>;

export function GetTrimWaveform(arg1:string,arg2:number):Promise<media.WaveformResult>;

export function ListTrimBackups(arg1:string):Promise<Array<media.TrimBackup>>;

export function LoadAudio(arg1:string):Promise<void>;

export function LoadLibrary():Promise<Array<string>>;

export function LoadLibraryWithMetadata():Promise<library.BatchResult>;

export function LoadMetadata(arg1:string):Promise<metadata.TrackMetadata>;

export function PauseAudio():Promise<void>;

export function PlayAudio():Promise<void>;

export function ResetAppData():Promise<void>;

export function RestoreTrimBackup(arg1:string):Promise<main.TrimResult>;

export function SaveLibrary(arg1:Array<string>):Promise<void>;

export function SaveMetadata(arg1:metadata.TrackMetadata):Promise<void>;

export function SaveMetadataAndRefresh(arg1:metadata.TrackMetadata):Promise<metadata.TrackMetadata>;

export function SeekAudio(arg1:number):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectVideoFile():Promise<string>;

export function SetDownloaderAutoStart(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function SoundCloudBeginAuth():Promise<string>;

export function SoundCloudListLikes(arg1:string):Promise<soundcloud.LikesPage>;

export function SoundCloudLogout():Promise<void>;

export function SoundCloudSetCredentials(arg1:string,arg2:string):Promise<void>;

export function SoundCloudStatus():Promise<soundcloud.AuthStatus>;

export function SoundCloudValidateCredentials():Promise<void>;

export function StartDownloader():Promise<void>;

export function StopDownloader():Promise<void>;

export function ToggleAudio():Promise<boolean>;

export function TrimTrack(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.TrimResult>;
