// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function ChooseDownloadFolder() {
  return window['go']['main']['App']['ChooseDownloadFolder']();
}

export function DownloadMedia(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadMedia'](arg1, arg2, arg3, arg4);
}

export function DownloaderStatus() {
  return window['go']['main']['App']['DownloaderStatus']();
}

export function GetAudioState() {
  return window['go']['main']['App']['GetAudioState']();
}

export function GetDownloaderAutoStart() {
  return window['go']['main']['App']['GetDownloaderAutoStart']();
}

export function LoadAudio(arg1) {
  return window['go']['main']['App']['LoadAudio'](arg1);
}

export function LoadLibrary() {
  return window['go']['main']['App']['LoadLibrary']();
}

export function LoadLibraryWithMetadata() {
  return window['go']['main']['App']['LoadLibraryWithMetadata']();
}

export function LoadMetadata(arg1) {
  return window['go']['main']['App']['LoadMetadata'](arg1);
}

export function PauseAudio() {
  return window['go']['main']['App']['PauseAudio']();
}

export function PlayAudio() {
  return window['go']['main']['App']['PlayAudio']();
}

export function ResetAppData() {
  return window['go']['main']['App']['ResetAppData']();
}

export function SaveLibrary(arg1) {
  return window['go']['main']['App']['SaveLibrary'](arg1);
}

export function SaveMetadata(arg1) {
  return window['go']['main']['App']['SaveMetadata'](arg1);
}

export function SaveMetadataAndRefresh(arg1) {
  return window['go']['main']['App']['SaveMetadataAndRefresh'](arg1);
}

export function SeekAudio(arg1) {
  return window['go']['main']['App']['SeekAudio'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SetDownloaderAutoStart(arg1) {
  return window['go']['main']['App']['SetDownloaderAutoStart'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function SoundCloudBeginAuth() {
  return window['go']['main']['App']['SoundCloudBeginAuth']();
}

export function SoundCloudListLikes(arg1) {
  return window['go']['main']['App']['SoundCloudListLikes'](arg1);
}

export function SoundCloudLogout() {
  return window['go']['main']['App']['SoundCloudLogout']();
}

export function SoundCloudSetCredentials(arg1, arg2) {
  return window['go']['main']['App']['SoundCloudSetCredentials'](arg1, arg2);
}

export function SoundCloudStatus() {
  return window['go']['main']['App']['SoundCloudStatus']();
}

export function SoundCloudValidateCredentials() {
  return window['go']['main']['App']['SoundCloudValidateCredentials']();
}

export function StartDownloader() {
  return window['go']['main']['App']['StartDownloader']();
}

export function StopDownloader() {
  return window['go']['main']['App']['StopDownloader']();
}

export function ToggleAudio() {
  return window['go']['main']['App']['ToggleAudio']();
}
